purpose: []
color:
  saturation: 0.453434188850224
  brandStrength: 0.7584839484188706
  rhythmicContrast: 0.7567647427786142
  brandColors:
    - '#F8F2E2'
    - '#2E2A27'
    - '#E1CAAA'
    - '#B6A080'
    - '#786957'
  lightness: 0.8147252143826336
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Jules Dee - Author
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1386659366544336
layout_spectrum: 0.2606516
