name: Jules Dee - Author
favicon: null
layout_spectrum: 0.30894107394851744
typography_spectrum: 0.1386659366544336
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7584839484188706
  lightness: 0.8147252143826336
  saturation: 0.453434188850224
  rhythmicContrast: 0.7567647427786142
purpose: []
